name: Publish Package

on:
  pull_request: 
    branches: 
      - main
  push: 
    branches:
      - main

jobs:
  test:
    name: Run Tests (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest tests/ --maxfail==1 --disable-warnings -q

  build_and_publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    needs: []
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: pypi
    steps:
      - uses: action/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
